### ISSUE TITLE
Bug: Unexpected autocompletion

### ISSUE THREAD

**Issue by bracketsberlin** [Pushedskydiver/Colour-Contrast-Checker#42]
# Bug Report

**What is the current behaviour?**
When entering "#f0f0", the app autocompletes to "#ff00ff".

https://user-images.githubusercontent.com/20646553/172554556-915b3015-40eb-4746-8897-e12c8455b035.mov

**What is the expected behaviour?**
There should be no autocompletion for the given value, as values like "#F0F0F0" couldn't be entered otherwise.

**Please mention other relevant information.**
CHROME VERSION |   | 102.0.5005.61
OS VERSION |   | Mac OS X: 12.2.0

**Comment by Pushedskydiver** [comment]
Thank you for spotting this. I have found the cause of this issue and it should be resolved now.
